#!/bin/bash
if [ -f /sys/bus/pci/devices/0000:01:00.0/remove ]; then
  echo 'Detected Nvidia card bus'
  select opt in 'Turn it off' 'Leave it'; do
    case $opt in
      'Turn it off')
          sudo modprobe -r nvidia
          sudo sh -c 'echo 1 > /sys/bus/pci/devices/0000:01:00.0/remove'
        break;;
      'Leave it')
        break;;
    esac
  done
fi
