#!/usr/bin/env zsh
jira_set_issue() {
  JIRA_ISSUE=$(jira issue list --plain --project CLOUD -s~Done | fzf | awk '{print $2}') && \
  JIRA_ISSUE_SUMMARY="${JIRA_ISSUE}$(jira issue view --plain ${JIRA_ISSUE} | grep '#' | head -n 1 | sed -E -e 's/  +//g' -e 's/#//g')" && \
  JIRA_ISSUE_BRANCH=$(sed <<<"$JIRA_ISSUE_SUMMARY" -e 's/[\t#: ]\+/_/g' -e 's/_$//' -e 's/\.//g')

  echo "JIRA_ISSUE: ${JIRA_ISSUE}"
  echo "JIRA_ISSUE_SUMMARY: ${JIRA_ISSUE_SUMMARY}"
  echo "JIRA_ISSUE_BRANCH: ${JIRA_ISSUE_BRANCH}"
}
