#!/usr/bin/env bash

nvim_bin=$(which nvim)

# attach to an existing nvim instance or start a new one
function nvim_remote() {
  nvr -s --nostart "$@" || $nvim_bin "$@"
}

# automatically jump to the tmux window and pane hosting nvim
function jump_to_nvim() {
  for window in $(tmux list-window -F '#{window_id}'); do
    pane=$(tmux list-panes -t "${window}" -F '#{pane_id} #{pane_current_command}' | awk '/nvim/ {print $1}')
    if [[ ${pane} != "" ]]; then
      tmux select-window -t "${window}"
      tmux select-pane -t "${pane}"
      break
    fi
  done
}

# only use one instance of nvim and auto-switch focus
function nvim() {
  jump_to_nvim
  nvim_remote "$@"
}
